export const SPECIALTIES = [
  'Medicina General / Clínica Médica',
  'Pediatría',
  'Cardiología',
  'Dermatología',
  'Ginecología y Obstetricia',
  'Neurología',
  'Traumatología y Ortopedia',
  'Oftalmología',
  'Psiquiatría',
  'Psicología',
  'Otorrinolaringología',
  'Urología',
  'Gastroenterología',
  'Endocrinología',
  'Oncología',
  'Reumatología',
  'Hematología',
  'Neumología',
  'Nefrología',
  'Infectología',
  'Cirugía General',
  'Medicina Interna',
  'Nutrición y Dietética',
  'Fisiatría y Rehabilitación',
  'Radiología',
] as const

export const DAYS_OF_WEEK = [
  'Lunes',
  'Martes',
  'Miércoles',
  'Jueves',
  'Viernes',
  'Sábado',
  'Domingo',
] as const

export const ZONES: Record<string, string[]> = {
  Montevideo: [
    'Aguada',
    'Atahualpa',
    'Belvedere',
    'Buceo',
    'Capurro',
    'Carrasco',
    'Carrasco Norte',
    'Casavalle',
    'Centro',
    'Cerrito',
    'Cerro',
    'Ciudad Vieja',
    'Colón',
    'Cordón',
    'Figurita',
    'Flor de Maroñas',
    'Goes',
    'Ituzaingó',
    'Jacinto Vera',
    'La Blanqueada',
    'La Teja',
    'La Unión',
    'Larrañaga',
    'Lezica',
    'Malvín',
    'Malvín Norte',
    'Manga',
    'Maroñas',
    'Nuevo París',
    'Palermo',
    'Parque Batlle',
    'Parque Rodó',
    'Paso de la Arena',
    'Peñarol',
    'Piedras Blancas',
    'Pocitos',
    'Prado',
    'Punta Carretas',
    'Punta de Rieles',
    'Reducto',
    'Sayago',
    'Tres Cruces',
    'Villa Española',
    'Villa García',
  ],
  Canelones: [
    'Ciudad de la Costa',
    'Las Piedras',
    'La Paz',
    'Progreso',
    'Pando',
    'Atlántida',
    'Salinas',
    'Barros Blancos',
    'San Jacinto',
    'Canelones ciudad',
  ],
  Maldonado: [
    'Maldonado ciudad',
    'Punta del Este',
    'San Carlos',
    'Piriápolis',
    'Pan de Azúcar',
  ],
  Colonia: ['Colonia del Sacramento', 'Nueva Helvecia', 'Carmelo', 'Juan Lacaze', 'Rosario'],
  'San José': ['San José de Mayo', 'Libertad', 'Ciudad del Plata'],
  Salto: ['Salto ciudad', 'Constitución'],
  Paysandú: ['Paysandú ciudad', 'Guichón'],
  Rivera: ['Rivera ciudad', 'Tranqueras'],
  Tacuarembó: ['Tacuarembó ciudad', 'Paso de los Toros'],
  Rocha: ['Rocha ciudad', 'Chuy', 'La Paloma', 'Castillos'],
  'Treinta y Tres': ['Treinta y Tres ciudad', 'Vergara'],
  'Cerro Largo': ['Melo', 'Río Branco'],
  Florida: ['Florida ciudad', 'Sarandí Grande'],
  Flores: ['Trinidad'],
  Durazno: ['Durazno ciudad', 'Santa Bernardina'],
  Soriano: ['Mercedes', 'Dolores'],
  'Río Negro': ['Fray Bentos', 'Young'],
  Artigas: ['Artigas ciudad', 'Bella Unión'],
  Lavalleja: ['Minas'],
}

export const DEPARTMENTS = Object.keys(ZONES)

export const STATUS_LABELS: Record<string, string> = {
  pending: 'Pendiente',
  accepted: 'Confirmada',
  rejected: 'Rechazada',
  cancelled: 'Cancelada',
  pending_payment: 'Pago pendiente',
}

export const URGENCY_FEE = 300
